package nl.vu.nat.tgmeditor.panels;

import javax.swing.JComponent;
import nl.vu.nat.tgmfilesupport.TgmDataObject;
import nl.vu.nat.tgmodels.tgm.FlimPanelModel;
import org.netbeans.modules.xml.multiview.ui.SectionInnerPanel;

/*
 * KinFlimPanel.java
 *
 * Created on August 1, 2008, 4:46 PM
 */
import org.netbeans.modules.xml.multiview.ui.SectionView;

/**
 *
 * @author  kate
 */
public class FlimPanel extends SectionInnerPanel {

    private TgmDataObject dObj;
    private FlimPanelModel flimPanelModel;

    public FlimPanel(SectionView view, TgmDataObject dObj, FlimPanelModel flimPanelModel) {
        super(view);
        this.dObj = dObj;
        this.flimPanelModel = flimPanelModel;
        initComponents();
        if (flimPanelModel.isMirf()) {
            JRbMirf_True.setSelected(true);
        } else if (!flimPanelModel.isMirf()){
            JRbMirf_False.setSelected(true);
            flimPanelModel.setMirf(false); endUIChange();
        } else {
            JRbMirf_False.setSelected(true);
            flimPanelModel.setMirf(false); endUIChange();
        }
        
        switch (flimPanelModel.getConvalg()) {
            case 1:
                jRbConvalg_1.setSelected(true);
                break;
            case 2:
                jRbConvalg_2.setSelected(true);
                break;
            case 3:
                jRbConvalg_3.setSelected(true);
                break;
            default: {
                jRbConvalg_1.setSelected(true);
                flimPanelModel.setConvalg(1); endUIChange();
                break;
            }
        } //end switch
        jTReftauTextField.setText(String.valueOf(flimPanelModel.getReftau()));

        addModifier(jRbConvalg_1);
        addModifier(jRbConvalg_2);
        addModifier(jRbConvalg_3);
        addModifier(jTReftauTextField);
        addModifier(JRbMirf_False);
        addModifier(JRbMirf_True);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRbConvalg_1 = new javax.swing.JRadioButton();
        jRbConvalg_2 = new javax.swing.JRadioButton();
        jRbConvalg_3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTReftauTextField = new javax.swing.JTextField();
        JRbMirf_False = new javax.swing.JRadioButton();
        JRbMirf_True = new javax.swing.JRadioButton();

        jLabel1.setText("Is a measured IRF specified?");

        jLabel2.setText("Select an algorithm for numerical convolution of IRF");

        buttonGroup2.add(jRbConvalg_1);
        jRbConvalg_1.setSelected(true);
        jRbConvalg_1.setText("Scatter algorithm 1");

        buttonGroup2.add(jRbConvalg_2);
        jRbConvalg_2.setText("Scatter algorithm 2");

        buttonGroup2.add(jRbConvalg_3);
        jRbConvalg_3.setText("Reference algorithm 1 (requires a reference lifetime to be given below)");
        jRbConvalg_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbConvalg_3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Specify a reference lifetime for use with Reference algorithm 1:");

        jTReftauTextField.setColumns(10);
        jTReftauTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTReftauTextFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRbMirf_False);
        JRbMirf_False.setSelected(true);
        JRbMirf_False.setText("No");
        JRbMirf_False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRbMirf_FalseActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRbMirf_True);
        JRbMirf_True.setText("Yes (specified with dataset)");
        JRbMirf_True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRbMirf_TrueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JRbMirf_False)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRbMirf_True))
                    .addComponent(jLabel2)
                    .addComponent(jRbConvalg_3)
                    .addComponent(jRbConvalg_2)
                    .addComponent(jRbConvalg_1)
                    .addComponent(jLabel3)
                    .addComponent(jTReftauTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRbMirf_False)
                    .addComponent(JRbMirf_True))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jRbConvalg_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbConvalg_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbConvalg_3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTReftauTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jRbConvalg_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbConvalg_3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRbConvalg_3ActionPerformed

private void jTReftauTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTReftauTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTReftauTextFieldActionPerformed

private void JRbMirf_FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRbMirf_FalseActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_JRbMirf_FalseActionPerformed

private void JRbMirf_TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRbMirf_TrueActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_JRbMirf_TrueActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRbMirf_False;
    private javax.swing.JRadioButton JRbMirf_True;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRbConvalg_1;
    private javax.swing.JRadioButton jRbConvalg_2;
    private javax.swing.JRadioButton jRbConvalg_3;
    private javax.swing.JTextField jTReftauTextField;
    // End of variables declaration//GEN-END:variables
    @Override
    public void setValue(JComponent source, Object value) {
        if (source == JRbMirf_True) {
            flimPanelModel.setMirf(true);
        }
        if (source == JRbMirf_False) {
            flimPanelModel.setMirf(false);
        }
        if (source==jRbConvalg_1) {
            if((Boolean)value) flimPanelModel.setConvalg(1);
        }
        if (source==jRbConvalg_2) {
            if((Boolean)value) flimPanelModel.setConvalg(1);
        }
        if (source==jRbConvalg_3) {
            if((Boolean)value) flimPanelModel.setConvalg(1);
        }
        if (source == jTReftauTextField) {
            flimPanelModel.setReftau((Double)value);
        }
        endUIChange();
    }

    public void linkButtonPressed(Object arg0, String arg1) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public JComponent getErrorComponent(String arg0) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    protected void endUIChange() {// signalUIChange() is deprecated{
        dObj.modelUpdatedFromUI();
    }
}
