/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.timpgui.gui.scheme;

import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.timpgui.gui.scheme.palette.PaletteSupport;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class SchemeDesignTopComponent extends TopComponent {

    private static SchemeDesignTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "SchemeDesignTopComponent";
    private TIMPGUIScene scene = new TIMPGUIScene();

    private SchemeDesignTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(SchemeDesignTopComponent.class, "CTL_SchemeDesignTopComponent"));
        setToolTipText(NbBundle.getMessage(SchemeDesignTopComponent.class, "HINT_SchemeDesignTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        jScrollPane1.setViewportView(scene.createView());
        //jPanel2.add(scene.createView());
        jPanel1.add(scene.createSatelliteView());
        associateLookup( Lookups.fixed( new Object[] { PaletteSupport.createPalette() } ) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(600);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(jPanel2);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized SchemeDesignTopComponent getDefault() {
        if (instance == null) {
            instance = new SchemeDesignTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the SchemeDesignTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized SchemeDesignTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(SchemeDesignTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof SchemeDesignTopComponent) {
            return (SchemeDesignTopComponent) win;
        }
        Logger.getLogger(SchemeDesignTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return SchemeDesignTopComponent.getDefault();
        }
    }
}
