//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.11 at 05:00:46 PM CEST 
//


package nl.vu.nat.tgmodels.tgm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.vu.nat.tgmodels.tgm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vu.nat.tgmodels.tgm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KinPar }
     * 
     */
    public KinPar createKinPar() {
        return new KinPar();
    }

    /**
     * Create an instance of {@link IrfparPanelModel }
     * 
     */
    public IrfparPanelModel createIrfparPanelModel() {
        return new IrfparPanelModel();
    }

    /**
     * Create an instance of {@link FlimPanelModel }
     * 
     */
    public FlimPanelModel createFlimPanelModel() {
        return new FlimPanelModel();
    }

    /**
     * Create an instance of {@link KinparPanelModel }
     * 
     */
    public KinparPanelModel createKinparPanelModel() {
        return new KinparPanelModel();
    }

    /**
     * Create an instance of {@link Cohspec }
     * 
     */
    public Cohspec createCohspec() {
        return new Cohspec();
    }

    /**
     * Create an instance of {@link Dat }
     * 
     */
    public Dat createDat() {
        return new Dat();
    }

    /**
     * Create an instance of {@link Tgm }
     * 
     */
    public Tgm createTgm() {
        return new Tgm();
    }

    /**
     * Create an instance of {@link CohspecPanelModel }
     * 
     */
    public CohspecPanelModel createCohspecPanelModel() {
        return new CohspecPanelModel();
    }

}
