//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.11 at 05:00:46 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nat.vu.nl/~jsnel/Schema/TgmSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.vu.nat.tgmodels.tgm;
