/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DatasetContainerComponent.java
 *
 * Created on Jul 15, 2009, 10:18:18 AM
 */

package org.glotaran.core.ui.visualmodelling.components;

import java.awt.BorderLayout;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import org.glotaran.core.main.nodes.TimpDatasetNode;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.AbstractNode;
import org.openide.util.Lookup;

/**
 *
 * @author slk230
 */
public class DatasetContainerComponent extends javax.swing.JPanel implements ExplorerManager.Provider, Lookup.Provider {

/** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "DatasetsListView";

    private ExplorerManager manager   = new ExplorerManager();
    private DatasetView    datasetView  = new DatasetView();
    private DatasetNodeContainer   container = new DatasetNodeContainer();
    private Lookup lookup;

    /** Creates new form DatasetContainerComponent */
    public DatasetContainerComponent() {
        initComponents();
        jPDatasetsPanel.add(datasetView);
        manager.setRootContext(new AbstractNode(container));//,ExplorerUtils.createLookup(manager, null)));
        //new ProxyLookup(arg0)

        // Add a drop target to the JPanel



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        modelDiffsScrollPane = new javax.swing.JScrollPane();
        modelDiffsPanel = new javax.swing.JPanel();
        datasetsScrollPane = new javax.swing.JScrollPane();
        jPDatasetsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(160, 250));
        setMinimumSize(new java.awt.Dimension(160, 250));
        setPreferredSize(new java.awt.Dimension(160, 250));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        modelDiffsScrollPane.setViewportView(modelDiffsPanel);

        jSplitPane1.setRightComponent(modelDiffsScrollPane);

        datasetsScrollPane.setViewportView(jPDatasetsPanel);

        jSplitPane1.setLeftComponent(datasetsScrollPane);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane datasetsScrollPane;
    private javax.swing.JPanel jPDatasetsPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel modelDiffsPanel;
    private javax.swing.JScrollPane modelDiffsScrollPane;
    // End of variables declaration//GEN-END:variables

    public ExplorerManager getExplorerManager() {
        return manager;
    }

    public Lookup getLookup() {
        return lookup;
    }

}
