//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.05 at 05:24:30 PM CET 
//


package org.glotaran.core.models.gta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Layout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Layout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="xposition" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="yposition" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Layout", propOrder = {
    "height",
    "width",
    "xposition",
    "yposition"
})
public class Layout {

    @XmlElement(required = true)
    protected Object height;
    @XmlElement(required = true)
    protected Object width;
    @XmlElement(required = true)
    protected Object xposition;
    @XmlElement(required = true)
    protected Object yposition;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHeight(Object value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWidth(Object value) {
        this.width = value;
    }

    /**
     * Gets the value of the xposition property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getXposition() {
        return xposition;
    }

    /**
     * Sets the value of the xposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXposition(Object value) {
        this.xposition = value;
    }

    /**
     * Gets the value of the yposition property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getYposition() {
        return yposition;
    }

    /**
     * Sets the value of the yposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setYposition(Object value) {
        this.yposition = value;
    }

}
