//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.05 at 05:24:30 PM CET 
//


package org.glotaran.core.models.gta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelDiffDO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelDiffDO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="what" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="dataset" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelDiffDO", propOrder = {
    "what",
    "index",
    "dataset",
    "start"
})
public class ModelDiffDO {

    @XmlElement(required = true)
    protected Object what;
    @XmlElement(required = true)
    protected Object index;
    @XmlElement(required = true)
    protected Object dataset;
    @XmlElement(required = true)
    protected Object start;

    /**
     * Gets the value of the what property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWhat() {
        return what;
    }

    /**
     * Sets the value of the what property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWhat(Object value) {
        this.what = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIndex(Object value) {
        this.index = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDataset(Object value) {
        this.dataset = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStart(Object value) {
        this.start = value;
    }

}
