//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.23 at 12:05:48 PM CET 
//


package nl.vu.nat.tgmodels.tgo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.vu.nat.tgmodels.tgo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vu.nat.tgmodels.tgo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OutputPanelElements.Output }
     * 
     */
    public OutputPanelElements.Output createOutputPanelElementsOutput() {
        return new OutputPanelElements.Output();
    }

    /**
     * Create an instance of {@link OptPanelElements }
     * 
     */
    public OptPanelElements createOptPanelElements() {
        return new OptPanelElements();
    }

    /**
     * Create an instance of {@link AlgorithmPanelElements }
     * 
     */
    public AlgorithmPanelElements createAlgorithmPanelElements() {
        return new AlgorithmPanelElements();
    }

    /**
     * Create an instance of {@link Tgo }
     * 
     */
    public Tgo createTgo() {
        return new Tgo();
    }

    /**
     * Create an instance of {@link IterPanelElements }
     * 
     */
    public IterPanelElements createIterPanelElements() {
        return new IterPanelElements();
    }

    /**
     * Create an instance of {@link OutputPanelElements }
     * 
     */
    public OutputPanelElements createOutputPanelElements() {
        return new OutputPanelElements();
    }

}
