/*
 * AlgorithmPanel.java
 *
 * Created on August 3, 2008, 1:22 PM
 */
package nl.vu.nat.tgoeditor.panels;

import nl.vu.nat.tgofilesupport.TgoDataObject;
import javax.swing.JComponent;

import nl.vu.nat.tgmodels.tgo.AlgorithmPanelElements;
import org.netbeans.modules.xml.multiview.ui.SectionInnerPanel;
import org.netbeans.modules.xml.multiview.ui.SectionView;

/**
 *
 * @author  kate
 */
public class AlgorithmPanel extends SectionInnerPanel {

    private TgoDataObject dObj;
    private AlgorithmPanelElements algorithmData;

    /** Creates new form AlgorithmPanel */
    public AlgorithmPanel(SectionView view, TgoDataObject dObj, AlgorithmPanelElements algorithmData) {
        super(view);
        this.dObj = dObj;
        this.algorithmData = algorithmData;
        initComponents();
        
        if (algorithmData.getAlgorithm().compareTo("nls")==0) {
            jRadioButton1.setSelected(true);}
        else if (algorithmData.getAlgorithm().compareTo("nls.lm")==0) {
            jRadioButton2.setSelected(true);}
        else if (algorithmData.getAlgorithm().compareTo("optim")==0) {
            jRadioButton3.setSelected(true);}
        else {jRadioButton1.setSelected(true);
        algorithmData.setAlgorithm("nls"); endUIChange();
        }
        
        if (algorithmData.isNnls()) {
            jRadioButton5.setSelected(true);
        } else {
            jRadioButton4.setSelected(true);
            algorithmData.setNnls(false); endUIChange();
        }
        if (algorithmData.isStderrclp()) {
            jRadioButton7.setSelected(true);
        } else {
            jRadioButton6.setSelected(true);
            algorithmData.setStderrclp(false); endUIChange();
        }

        addModifier(jRadioButton1);
        addModifier(jRadioButton2);
        addModifier(jRadioButton3);
        addModifier(jRadioButton4);
        addModifier(jRadioButton5);
        addModifier(jRadioButton6);
        addModifier(jRadioButton7);

        }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        jLabel1.setText("Algorithm");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("nls");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("nls.lm");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("optim");

        jLabel2.setText("Constrain clp to non-negative values?");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("No");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Yes");

        jLabel3.setText("Determine standard errors of clp?");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("No");

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void setValue(JComponent source, Object value) {
        if (source == jRadioButton1) {
            if ((Boolean)value) {
            algorithmData.setAlgorithm("nls");
            }
        }
        if (source == jRadioButton2) {
            if ((Boolean)value) {
            algorithmData.setAlgorithm("nls.lm");
            }
        }
        if (source == jRadioButton3) {
            if ((Boolean)value) {
            algorithmData.setAlgorithm("optim");
            }
        }
        if (source == jRadioButton4) {
            if ((Boolean)value) {
            algorithmData.setNnls(false);
            }
        }
        if (source == jRadioButton5) {
            if ((Boolean)value) {
            algorithmData.setNnls(true);
            }
        }
        if (source == jRadioButton6) {
            if ((Boolean)value) {
            algorithmData.setStderrclp(false);
            }
        }
        if (source == jRadioButton7) {
            if ((Boolean)value) {
            algorithmData.setStderrclp(true);
            }
        }
        endUIChange();
    } //endof setValue(...);

    @Override
    protected void endUIChange() { //signalUIChange() {
        dObj.modelUpdatedFromUI();
    }

    public void linkButtonPressed(Object arg0, String arg1) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public JComponent getErrorComponent(String arg0) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
